### ISSUE TITLE
"System.TypeLoadException: Context-bound objects with generic methods are not supported."

### ISSUE THREAD

**Issue by WasiqB** [timschlechter/SpecResults.WebApp#5]
Hi,

![image](https://cloud.githubusercontent.com/assets/9130909/8248298/d5d83cc0-167a-11e5-80e8-6e83ff3c33c1.png)

Since yesterday evening we are facing this issue while running Unit Test. Following is the code snippet which I have found that is causing the problem:

[Binding]
public class BaseTest : ReportingStepDefinitions {
...
}

If I change this code to 

[Binding]
public class BaseTest : Steps {
...
}

Then it runs successfully.

Kindly let me know what is causing this issue.

Note: -
Complete StackTrace of Error:
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at NUnit.Core.CoreExtensions.InstallAdhocExtensions(Assembly assembly)
   at NUnit.Core.Builders.TestAssemblyBuilder.Load(String path)
   at NUnit.Core.Builders.TestAssemblyBuilder.Build(String assemblyName, Boolean autoSuites)
   at NUnit.Core.Builders.TestAssemblyBuilder.Build(String assemblyName, String testName, Boolean autoSuites)
   at NUnit.Core.TestSuiteBuilder.Build(TestPackage package)
   at NUnit.Core.SimpleTestRunner.Load(TestPackage package)
   at NUnit.Core.ProxyTestRunner.Load(TestPackage package)
   at NUnit.Core.RemoteTestRunner.Load(TestPackage package)
   at JetBrains.ReSharper.UnitTestRunner.nUnit.BuiltInNUnitRunner.RunTests(IRemoteTaskServer server, Dictionary`2 tests, Dictionary`2 fixtures, List`1 explicitly, Boolean useAddins, List`1 assemblies)

**Comment by WasiqB** [comment]
I found the main cause of issue, it was due to some generic methods which I had added in BaseTest class. When I removed them, Unit Test is now working fine. My apologyse for inconvineince caused.
